[package]
name = "cli"
version = "0.1.0"
authors = ["shaipe <shaipe@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.4"
clap = {version="2.33.3",features = ["yaml"] }


[[bin]]
name = "dcli"
path = "./src/main.rs"
