[package]
name = "server"
version = "0.1.0"
authors = ["shaipe <shaipe@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-multipart = "0.3.0"
actix-web = "3.3.2"
futures = "0.3.12"
sanitize-filename = "0.3.0"
yaml-rust = "0.4.5"
tube_error = {version="0.1.0", path="../../tube/error"}
oss = {version="0.1.0", path="../../oss"}
tube_cmd = {version="0.1.0", path="../../tube/cmd"}

[[bin]]
name = "dserver"
path = "./src/main.rs"
